# Generated by Django 4.2.14 on 2024-09-01 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consum_position', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('storage_temp', models.CharField(max_length=100)),
                ('cat_number', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('consum_descr', models.TextField(default='N/A')),
                ('delivery_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='consumables/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_consumables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reagents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_position', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('storage_temp', models.CharField(max_length=100)),
                ('cat_number', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('reagent_descr', models.TextField(default='N/A')),
                ('delivery_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reagents/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_reagents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='user_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents_user_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReagentsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=10)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='reagents.reagents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reagent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ConsumablesAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=10)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='reagents.consumables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('consumable', 'user')},
            },
        ),
    ]
