# Generated by Django 4.2.14 on 2024-09-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagents',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
