# Generated by Django 4.2.14 on 2024-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0003_rename_reagent_descr_reagents_reagent_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumables',
            old_name='consum_descr',
            new_name='consumable_descr',
        ),
        migrations.RemoveField(
            model_name='consumables',
            name='consum_position',
        ),
        migrations.AddField(
            model_name='consumables',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
