# Generated by Django 4.2.14 on 2024-08-29 14:32

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_birth_date_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=users.models.NameField(max_length=100),
        ),
    ]
