# Generated by Django 5.1 on 2024-08-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_rename_description_progress_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='project',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='project',
        ),
        migrations.RemoveField(
            model_name='method',
            name='project',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='project',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='Literature',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
