# Generated by Django 4.2.14 on 2024-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='protocol_text',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='protocols/'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
