# Generated by Django 4.2.14 on 2024-08-21 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocols', '0006_protocol_protocol_text_alter_protocol_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols_user_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
