# Generated by Django 4.2.14 on 2024-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_owner_projectaccess'),
        ('protocols', '0007_alter_userfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='protocols', to='projects.project'),
        ),
    ]
