# Generated by Django 4.2.14 on 2024-09-03 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_owner_projectaccess'),
        ('reagents', '0003_rename_reagent_descr_reagents_reagent_description_and_more'),
        ('protocols', '0008_protocol_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='user_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_user_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_action', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_topic', models.CharField(max_length=150)),
                ('note_text', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=10)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reagents.consumables')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_notes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='protocols.protocol')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reagents.reagents')),
            ],
        ),
        migrations.CreateModel(
            name='NoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=10)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='notes.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('note', 'user')},
            },
        ),
    ]
