# Generated by Django 4.2.14 on 2024-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0004_rename_consum_descr_consumables_consumable_descr_and_more'),
        ('projects', '0002_alter_project_owner_projectaccess'),
        ('protocols', '0008_protocol_projects'),
        ('notes', '0002_alter_notes_note_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='reagent',
        ),
        migrations.AddField(
            model_name='notes',
            name='consumables',
            field=models.ManyToManyField(blank=True, related_name='notes', to='reagents.consumables'),
        ),
        migrations.AddField(
            model_name='notes',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='notes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='notes',
            name='protocols',
            field=models.ManyToManyField(blank=True, related_name='notes', to='protocols.protocol'),
        ),
        migrations.AddField(
            model_name='notes',
            name='reagents',
            field=models.ManyToManyField(blank=True, related_name='notes', to='reagents.reagents'),
        ),
    ]
